# Generated by Django 4.1.4 on 2022-12-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='poster/')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
