# Generated by Django 4.1.4 on 2022-12-08 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_otpcodemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcodemodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='otpcodemodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
