# Generated by Django 4.1.4 on 2022-12-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_alter_categorymodel_slug_typeproductmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='img',
            field=models.ImageField(null=True, upload_to='category/img'),
        ),
        migrations.AlterField(
            model_name='typeproductmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='category/img'),
        ),
        migrations.AlterField(
            model_name='typeproductmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='آدرس لینک'),
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_to_category', to='Category.categorymodel')),
            ],
        ),
    ]
