# Generated by Django 4.1.4 on 2022-12-09 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Category', '0004_alter_categorymodel_img_alter_typeproductmodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('off_price', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.JSONField(blank=True, default=dict, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('star', models.JSONField(blank=True, default=dict, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_to_brand', to='Category.brandmodel')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_to_category', to='Category.categorymodel')),
                ('like', models.ManyToManyField(blank=True, related_name='like_product', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_to_type', to='Category.typeproductmodel')),
            ],
            options={
                'ordering': ('-like_count',),
            },
        ),
    ]
