# Generated by Django 4.1.4 on 2022-12-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_rename_price_productmodel_all_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
