# Generated by Django 4.1.4 on 2022-12-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0007_productmodel_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iproduct', to='Category.productmodel')),
            ],
        ),
    ]
