# Generated by Django 4.1.4 on 2022-12-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0008_imageproductmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproductmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_to_product', to='Category.productmodel'),
        ),
    ]
