# Generated by Django 4.1.4 on 2022-12-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0010_imagdeslidmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagdeSlidModel',
        ),
    ]
