# Generated by Django 4.1.4 on 2022-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0012_imagdeslidmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='des',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
