# Generated by Django 4.1.4 on 2022-12-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0013_brandmodel_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagdeslidmodel',
            name='des',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagdeslidmodel',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
