# Generated by Django 4.1.4 on 2022-12-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_option', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='replaycommentmodel',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replycomment_to_comment', to='Product_option.commentmodel'),
        ),
    ]
