# Generated by Django 4.1.4 on 2022-12-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0003_ordermodel_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='user_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderview_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
