# Generated by Django 4.1.4 on 2023-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_ordermodel_user_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ref_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
